#
/control/verbose 2
/run/verbose 0
/tracking/verbose 0
#
/sndwrm/det/setGDMLfile /rcfs/projects/dunelb/jime782/duneggd/python/duneggd/apexfd/duneapex.gdml
/sndwrm/det/setHalfFidVol 7 7 32 m
/random/setSeeds 1 11
#
/run/numberOfThreads 1
/run/initialize
/process/list
#
# ---------- K-40 single gamma line at 1460.822 keV ----------
/gps/particle gamma
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 7 m
/gps/pos/halfy 7 m
/gps/pos/halfz 32 m
/gps/pos/centre 0 0 0 m
/gps/pos/confine Arapuca_place
/gps/ang/type iso
/gps/ene/type Mono
/gps/energy 1460.822 keV

/gps/source/list
#
/analysis/setFileName /rcfs/projects/dunelb/jime782/sndwrm/build/araK40_277.root
/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
/analysis/ntuple/setActivation 3 false
/analysis/ntuple/setActivation 4 false
#
/run/printProgress 25
# 2624 decays × 0.1055 γ/decay ≈ 277 gammas in a 10 s window
/run/beamOn 277
