#
#                                                                         
/control/verbose 2
/run/verbose 0
/tracking/verbose 0
#
# set the target/detector geometry
/sndwrm/det/setGDMLfile /rcfs/projects/dunelb/jime782/duneggd/python/duneggd/apexfd/duneapex.gdml
/sndwrm/det/setHalfFidVol 7 7 32 m
#/sndwrm/det/setHalfFidVol 651.486 672.371 2986.371 cm
#
/run/initialize
#
/process/list
#

/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 7 m           
/gps/pos/halfy 7 m
/gps/pos/halfz 32 m
/gps/pos/centre 0 0 0 m
/gps/pos/confine Arapuca_place

/gps/particle gamma
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file /rcfs/projects/dunelb/jime782/sndwrm/build/gamma_hist.txt
/gps/hist/inter Lin

/gps/ang/type iso

#
/analysis/setFileName /rcfs/projects/dunelb/jime782/sndwrm/build/gammaHistTEST.root

# Set histogram binning 

/analysis/h1/set 0 100 0. 2. MeV
/analysis/h1/set 1 100 0. 2. MeV
/analysis/h1/set 6 100 0. 2. MeV
/analysis/ntuple/setActivation 0 true
/analysis/ntuple/setActivation 1 true
/analysis/ntuple/setActivation 2 true
# tracks
/analysis/ntuple/setActivation 3 true
# stepping
/analysis/ntuple/setActivation 4 false

#
/run/printProgress 1
/random/setSeeds 1 11

/run/beamOn 1000
